# -*- coding: utf-8 -*-
"""Activity in CPEN65: Area of a Circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KvPUfxpQE5XJQaXd6WSZX3yh8Z6asNQp
"""

class Circle:
    def __init__(self, pi, r, d):
        self.pi = pi
        self.r = r
        self.d = d

    def Area(self):
        print(self.pi * self.r ** 2, "is the area of the circle ")

    def Area2(self):
        print("while", self.pi * self.d ** 2 / 4, "is the area of the circle using diameter ")


c = Circle (3.14159, 5, 8)
c.Area()
c.Area2()